<?php
$admin_permission = CheckAdminPermission($wo['user']['role_id'], "view_roles");

Redirect_dashboard($admin_permission);

$roles = GetRoles();
?>

<div class="container-fluid">
    <div class="block-header">
        <h2>Users > Manage Roles</h2>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 hvr-float-shadow">
            <div class="animated fadeInLeft delay-2s">
                <div class="card">
                    <div class="header"><!--
                    <h2>Manage & Edit Genders</h2>  -->
                        <div class="row">
                            <div class="col-md-12" style="margin-bottom:0;">
                                <div class=" add_category_form_alert"></div>
                                <div class="row">
                                    <div class="col-md-2">
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('create-roles'); ?>" class="btn btn-save btn-info">Add New Role</a>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                    <div class="body">
                        <div class="table-responsive1">
                            <table class="table table-bordered table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Permission Name</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                foreach ($roles as $role)
                                {?>
                                    <tr id="<?php echo  $role[0];?>">
                                        <td><?php echo $role[0];?></td>
                                        <td><?php echo $role[1];?></td>
                                        <td>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('edit-roles'); ?>?id=<?php echo  $role[0] ?>" class="btn btn-default btn-save waves-effect btn-lang m-r-20">EDIT</a>
                                            <button onclick="Wo_DeleteRole('<?php echo $role[0];?>');" type="button" class="btn btn-danger waves-effect waves-light">DELETE</button>
                                        </td>
                                    </tr>
                                <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- #END# Vertical Layout -->
<script>

    function Wo_DeleteRole(key) {
        if (key == '') {
            return false;
        }
        if (!confirm('Are you sure you want to delete this gender?')) {
            return false;
        }
        $('#' + key).fadeOut(300, function () {
            $(this).remove();
        });
        $.get(Wo_Ajax_Requests_File(), {f: 'admin_setting', s:'delete_role', key:key});
    }
</script>