<?php

$admin_permission = CheckAdminPermission($wo['user']['role_id'], "view_likes");

Redirect_dashboard($admin_permission);
?>


<div class="container-fluid">
    <div class="block-header">
        <h2>General User Tag  > Food Enjoyed </h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-3 col-md-3 hvr-float-shadow">
            <div class="animated fadeInLeft delay-2s">
                <div class="card">
                <div class="header">
                    <h2>Add Likes </h2>
                </div>
                <div class="body">

                  <div class="row">
                       <div class="col-md-12" style="margin-bottom:0;">
                        <div class=" add_category_form_alert"></div>
                            <form method="POST" id="add_category_form">
                              <div class="row">

                                    <div class="col-md-12" id="normal-query-form">
                                      <div class="form-group form-float">
                                          <div class="form-line">
                                              <input type="text" class="form-control" name="title">
                                              <label class="form-label">Likes</label>
                                          </div>
                                      </div>
                                    </div>

                                <div class="clearfix"></div>
                              <div class="col-md-2">
                                  <?php $admin_permission =  CheckAdminPermission($wo['user']['role_id'], "add_likes"); ?>
                                  <?php if($admin_permission == true) {?>
                                      <button class="btn btn-save btn-info">Add</button>
                                  <?php } ?>
                              </div>
                              </div>
                              <div class="clearfix"></div>
                           </form>
                       </div>
                   </div>
                </div>
            </div>
            </div>
        </div>
        <div class="col-lg-9 col-md-9 hvr-float-shadow">
            <div class="animated fadeInRight delay-2s">
                <div class="card">
                <div class="header">
                    <h2>Manage Likes </h2>
                </div>
                <div class="body">
                   <div class="clearfix"></div>
                   <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover js-basic-example">
                            <thead>
                                <tr>
                                      <th>ID</th>
					                  <th>Likes</th>
					                  <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php


                                global $sqlConnect, $wo;

                                $data = Wo_GetAllTableData(T_LIKES_S);
                                foreach ($data as $id => $title) {
                                  $wo['id'] = $id;
                                  $wo['title'] = $title;

                                	echo Wo_LoadAdminPage('likes/list');
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<div id="delete-modal" class="modal fade" role="dialog" data-id="">
  <div class="modal-dialog">
    <div class="modal-content modal-col-red">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">DELETE  Likes</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to continue? this action can't be undo</p>
      </div>
      <div class="modal-footer">
      	<button type="button" class="btn btn-link waves-effect" data-dismiss="modal" data-type="user" id="delete_category">DELETE</button>
        <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editcategoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal_content_back">
      <div class="modal-header">
        <h5 class="modal-title" id="editcategoryModalLabel">Edit  Likes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="edit_category_form_alert"></div>
        <form class="edit_category_lang" method="POST" id="modal-body-langs">
          <div class="data_lang"></div>
          <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
          <input type="hidden" name="id_of_key" id="id_of_key" value="">
        </form>
        
      </div>
      <div class="modal-footer">
        
        <button type="button" class="btn btn-secondary modal_close_btn" data-dismiss="modal">CLOSE</button>
        <button type="button" class="btn btn-primary" id="save_edited_category">SAVE CHANGES</button>
      </div>
    </div>
  </div>
</div>


<script>

var add_category_form = $('form#add_category_form');
var edit_category_form = $('form.edit_category_lang');

add_category_form.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=add_new_likes',
    beforeSend: function() {
        add_category_form.find('.waves-effect').text("Please wait..");
    },
    success: function(data) {
        if (data.status == 200) {
            add_category_form.find('.waves-effect').text('Save');
            $('.add_category_form_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i>  Likes successfully added</div>');
            setTimeout(function () {
                $('.add_category_form_alert').empty();
            }, 2000);
            window.location.reload();
        }
        else{
          $('.add_category_form_alert').html('<div class="alert alert-danger"><i class="fa fa-check"></i> '+data.message+'</div>');
            setTimeout(function () {
                $('.add_category_form_alert').empty();
            }, 2000);
        }
    }
});

edit_category_form.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_likes&hash=' + $('.main_session').val(),
    beforeSend: function() {
        edit_category_form.find('.waves-effect').text("Please wait..");
    },
    success: function(data) {
        if (data.status == 200) {
            edit_category_form.find('.waves-effect').text('Save');
            $('.edit_category_form_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i>  Likes successfully edited</div>');
            setTimeout(function () {
                $('.edit_category_form_alert').empty();
            }, 3000);
            window.location.reload();
        }
        else{
          $('.edit_category_form_alert').html('<div class="alert alert-danger"><i class="fa fa-check"></i> '+data.message+'</div>');
            setTimeout(function () {
                $('.edit_category_form_alert').empty();
            }, 2000);
        }
    }
});

$(document).on('click','#save_edited_category', function(event) {
  event.preventDefault();


  $('.edit_category_lang').submit();
});

function edit_category(id) {


  $('#id_of_key').val(id);
  $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=get_likes', {lang_key: id}, function(data, textStatus, xhr) {
      if (data.status == 200) {
        $('.data_lang').html(data.html);
        $('#editcategoryModal').modal();
      }
  });
}

$('.delete-content').on('click', function(event) {
    event.preventDefault();
    $('#delete-modal').attr('data-id', $(this).attr('data-id')).modal('show');
  });

$(document).on('click', '#delete_category', function(event) {
    event.preventDefault();
    lang_key = $('#delete-modal').attr('data-id');
    $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=delete_likes', {lang_key: lang_key}, function(data, textStatus, xhr) {
        if (data.status == 200) {
            $('#list-'+lang_key).slideUp('slow');
            setTimeout(function () {
                $('#list-'+lang_key).remove();
            },2000);
        }
    });
});



</script>