<?php

$admin_permission = CheckAdminPermission($wo['user']['role_id'], "view_auto_friend");

Redirect_dashboard($admin_permission);

$data = explode(',', $wo['config']['auto_friend_users'] );


?>


<div class="container-fluid">
    <div class="block-header">
        <h2>Tools > Auto Friend</h2>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6 hrv-float-shadow">
            <div class="animated fadeInLeft delay-2s">
                <div class="card">
                <div class="header">
                    <h2>Auto Friend</h2> 
                    <br>
                    <small>When a user creates a new account, choose which users you would like to get auto friended.</small>
                </div>
                <div class="body">
                    <div id="warning"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="users" name="users" class="form-control" value="">
                                <label class="form-label">Username</label>
                            </div>
                            <div class="notifications-users-list"></div>
<!--                            <div class="form-line">-->
<!--                                <input data-role="tagsinput" id="blog_tags" name="blog_tags" type="text" class="form-control input-md" placeholder="--><?php //echo $wo['lang']['tags']; ?><!--">-->
<!--                            </div>-->
                        </div>
                        <div class="clearfix"></div><br>
                        <small>This process might take some time, you can check for your site changes after few minutes.</small><br>
                    <?php $admin_permission =  CheckAdminPermission($wo['user']['role_id'], "add_auto_friend"); ?>
                    <?php if($admin_permission == true) {?>
                      <button type="submit" class="btn btn-save btn-danger waves-effect waves-light m-t-20" id="users-btn">Save</button>
                    <?php } ?>
                </div>
            </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 hrv-float-shadow">
            <div class="animated fadeInLeft delay-2s">
                <div class="card">
                <div class="header">
                    <h2>Auto Friend Listing</h2>
                </div>
                <div class="body">
                    <div id="message"></div>
                    <table id="myTable" class="display hover compact">
                        <thead>
                        <tr>
                            <th>Sr</th>
                            <th>Username</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php $counter = 1 ?>
                            <?php foreach($data as $a_data) { ?>
                                <tr>
                                    <td><?php echo $counter ?></td>
                                    <td><?php echo $a_data ?></td>
                                    <td><button class="btn btn-primary row_remove" onclick="Remove_Auto_Friend('<?php echo $a_data; ?>')">Remove</button></td>
                                </tr>
                                <?php $counter++ ?>
                            <?php }?>
                        </tbody>
                    </table>
                </div>
            </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    </div>
<script>

    $(document).ready( function () {
        $('#myTable').DataTable();

    });

    function Wo_GetNotifiedUsers(self){

        if (!self || $("#sendforall").is(':checked')) {
            $(".notifications-users-list").empty();
            return false;
        }
        $.ajax({
            url: Wo_Ajax_Requests_File() + "?f=notifications&s=get-users",
            type: 'POST',
            data: {name: $('#users').val()},
        })
            .done(function(data) {
                if (data.status == 200) {
                    $(".notifications-users-list").html(data.html);
                }
                else{
                    $(".notifications-users-list").empty();
                }
            })
            .fail(function() {
                console.log("error");
            })
    }

    function Remove_Auto_Friend($value)
    {
        $(document.body).on('click', '.row_remove' ,function(){
            $(this).parent().parent().remove()
        });

        $.get(Wo_Ajax_Requests_File(), {
            f:'admin_setting',
            s: 'remove_auto_friend',
            users: $value
        }, function(data, textStatus, xhr) {
            $("#message").html('<div class="alert alert-success">User Removed</div>');
        });
    }

$(document).on('click', '#users-btn', function(event) {
	event.preventDefault();
	$(this).text('Please wait..');
	$.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'auto_friend', users: $('#users').val()}, function(data, textStatus, xhr) {
		if(data.status == 200)
        {
            $('#users-btn').text('Saved!');
            $('#warning').empty();
            $('#warning').append('<div class="alert alert-success">User Added</div>');
            setTimeout(function () {
                $('#users-btn').text('Save');
            }, 4000);
        }
		else{
            $('#warning').empty();
		    $('#warning').append('<div class="alert alert-warning">'+data.message+'</div>');
        }
	});
});
</script>