<?php


$admin_permission = CheckAdminPermission($wo['user']['role_id'], "view_groups");

Redirect_dashboard($admin_permission);


$page = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? Wo_Secure($_GET['query']) : '';
$filter_type = '';
$db->pageLimit = 50;


if (!empty($filter_keyword)) {
    $sql = "(
   ( `id`          LIKE '%$filter_keyword%' OR 
    `group_name`  LIKE '%$filter_keyword%' OR
    `group_title` LIKE '%$filter_keyword%' OR
    `about`       LIKE '%$filter_keyword%') and `is_bp` != 1 
  )";

    $groups = $db->where($sql)->orderBy('id', 'DESC')->objectbuilder()->paginate("group_members", $page);
} else {
    $groups = $db->objectbuilder()->orderBy('id', 'DESC')->paginate("group_members", $page);
}

if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
    header("Location: " . Wo_LoadAdminLinkSettings('manage-groups'));
    exit();
}

?>
<div class="container-fluid">
    <div class="block-header">
        <h2>Manage Features > Groups > Joined Groups</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-groups'); ?>"">
            <div class="col-lg-3 col-md-3  hvr-float-shadow m-b-30">
                <div class="dash-info-box bg-light-green hover-expand-effect animated fadeInLeft  delay-2s">
                    <div class="icon">
                        <i class="material-icons">people</i>
                    </div>
                    <div class="content">
                        <div class="text">TOTAL GROUPS</div>
                        <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllData('group'); ?>"
                             data-speed="1000" data-fresh-interval="20"></div>
                    </div>
                </div>
            </div>
        </a>
        <div class="col-lg-3 col-md-3  hvr-float-shadow m-b-30">
            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-joined-groups'); ?>">
                <div class="dash-info-box bg-cyan hover-expand-effect animated fadeInUp delay-2s">
                    <div class="icon">
                        <i class="material-icons">people_outline</i>
                    </div>
                    <div class="content">
                        <div class="text">JOINED GROUPS</div>
                        <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountGroupData('members'); ?>"
                             data-speed="1000" data-fresh-interval="20"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-3 col-md-3  hvr-float-shadow m-b-30">
            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-total-groups-posts'); ?>">
                <div class="dash-info-box bg-pink hover-expand-effect animated fadeInDown delay-2s">
                    <div class="icon">
                        <i class="material-icons">mode_edit</i>
                    </div>
                    <div class="content">
                        <div class="text">TOTAL POSTS</div>
                        <div class="number count-to" data-from="0"
                             data-to="<?php echo Wo_CountGroupData('groups_posts'); ?>" data-speed="1000"
                             data-fresh-interval="20"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-3 col-md-3  hvr-float-shadow m-b-30">
            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-groups-join-request'); ?>">
                <div class="dash-info-box bg-purple hover-expand-effect animated fadeInRight">
                    <div class="icon">
                        <i class="material-icons">library_add</i>
                    </div>
                    <div class="content">
                        <div class="text">JOIN REQUESTS</div>
                        <div class="number count-to" data-from="0"
                             data-to="<?php echo Wo_CountGroupData('join_requests'); ?>" data-speed="1000"
                             data-fresh-interval="20"></div>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-lg-12 col-md-12">
            <div class="animated fadeInLeft  delay-2s">
                <div class="card">
                    <div class="header">
                        <h2>View Joined Groups</h2>
                    </div>
                    <div class="body">
                        <div class="table-responsive1">
                            <table class="table table-bordered table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Group Name</th>
                                    <th>Owner</th>
                                    <th>Category</th>
                                    <th>Group Created</th>
                                    <th>Group Members</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                foreach ($groups as $grouplist) {
                                    $wo['grouplist'] = Wo_GroupData($grouplist->group_id);
                                    $wo['grouplist']['owner'] = Wo_UserData($wo['grouplist']['user_id']);
                                    $wo['grouplist']['users'] = Wo_UserData($grouplist->user_id);
                                    if($wo['grouplist']['is_bp'] == 0)
                                    {
                                        echo Wo_LoadAdminPage('manage-joined-groups/list');
                                    }
                                }
                                ?>
                                </tbody>
                            </table>
                        </div>
                        <div class="wo-admincp-feturepager">
                            <div class="pull-left">
                            <span>
                              <?php echo "Showing $page out of " . $db->totalPages; ?>
                            </span>
                            </div>
                            <div class="pull-right">
                                <nav>
                                    <ul class="pagination">
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-groups?page-id=1'); ?>"
                                               class="waves-effect" title='First Page'>
                                                <i class="material-icons">first_page</i>
                                            </a>
                                        </li>
                                        <?php if ($page > 1) { ?>
                                            <li>
                                                <a href="<?php echo Wo_LoadAdminLinkSettings('manage-groups?page-id=' . ($page - 1)); ?>"
                                                   class="waves-effect" title='Previous Page'>
                                                    <i class="material-icons">chevron_left</i>
                                                </a>
                                            </li>
                                        <?php } ?>

                                        <?php
                                        $nums = 0;
                                        $nums_pages = ($page > 4) ? ($page - 4) : $page;

                                        for ($i = $nums_pages; $i <= $db->totalPages; $i++) {
                                            if ($nums < 20) {
                                                ?>
                                                <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                                    <a href="<?php echo Wo_LoadAdminLinkSettings('manage-groups?page-id=' . ($i)); ?>"
                                                       class="waves-effect">
                                                        <?php echo $i ?>
                                                    </a>
                                                </li>

                                            <?php }
                                            $nums++;
                                        } ?>

                                        <?php if ($db->totalPages > $page) { ?>
                                            <li>
                                                <a href="<?php echo Wo_LoadAdminLinkSettings('manage-groups?page-id=' . ($page + 1)); ?>"
                                                   class="waves-effect" title="Next Page">
                                                    <i class="material-icons">chevron_right</i>
                                                </a>
                                            </li>
                                        <?php } ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-groups?page-id=' . ($db->totalPages)); ?>"
                                               class="waves-effect" title='Last Page'>
                                                <i class="material-icons">last_page</i>
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <script>

        function Wo_DeleteGroup(group_id) {
            if (confirm("Are you sure you want to delete this group?") == false) {
                return false;
            }
            hash_id = $('#hash_id').val();
            $('#GroupID_' + group_id).fadeOut(300, function () {
                $(this).remove();
            });
            $.get(Wo_Ajax_Requests_File(), {
                f: 'admin_setting',
                s: 'delete_group',
                group_id: group_id,
                hash_id: hash_id
            });
        }

        function Wo_SuspendGroup(group_id, group_url, user_id, group_name) {
            if (confirm("Are you sure you want to suspend this page?") == false) {
                return false;
            }
            hash_id = $('#hash_id').val();
            // $('#PageID_' + page_id).fadeOut(300, function() {
            //   $(this).remove();
            // });
            $.get(Wo_Ajax_Requests_File(), {
                f: 'admin_setting',
                s: 'suspend_user_group',
                group_id: group_id,
                hash_id: hash_id,
                group_url: group_url,
                user_id: user_id,
                group_name: group_name
            });

            window.location.href = "<?php echo $wo['site_url'] ?>" + "/super-admin/manage-groups";

        }

        function Wo_UnSuspendGroup(group_id) {
            if (confirm("Are you sure you want to unsuspend this page?") == false) {
                return false;
            }
            hash_id = $('#hash_id').val();
            // $('#PageID_' + page_id).fadeOut(300, function() {
            //   $(this).remove();
            // });
            $.get(Wo_Ajax_Requests_File(), {
                f: 'admin_setting',
                s: 'unsuspend_user_group',
                group_id: group_id,
                hash_id: hash_id
            });

            window.location.href = "<?php echo $wo['site_url'] ?>" + "/super-admin/manage-groups";

        }

    </script>